services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      - N8N_HOST=n8n.etsrv.site
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.etsrv.site/
      - N8N_PROXY_HOPS=1
      - GENERIC_TIMEZONE=America/Panama
      - TZ=America/Panama
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
