"""Platform infrastructure — DB, shared adapters (Marketing OS M0+)."""

from .db import (
    brain_json_enabled,
    brain_sql_enabled,
    brain_store_mode,
    brand_json_enabled,
    brand_sql_enabled,
    brand_store_mode,
    ensure_schema,
    get_connection,
    get_db_path,
    memory_store_mode,
    memory_sql_enabled,
)

__all__ = [
    "brain_json_enabled",
    "brain_sql_enabled",
    "brain_store_mode",
    "brand_json_enabled",
    "brand_sql_enabled",
    "brand_store_mode",
    "ensure_schema",
    "get_connection",
    "get_db_path",
    "memory_store_mode",
    "memory_sql_enabled",
    "publication_json_enabled",
    "publication_sql_enabled",
    "publication_store_mode",
    "product_json_enabled",
    "product_sql_enabled",
    "product_store_mode",
    "knowledge_json_enabled",
    "knowledge_sql_enabled",
    "knowledge_store_mode",
    "campaign_json_enabled",
    "campaign_sql_enabled",
    "campaign_store_mode",
    "asset_json_enabled",
    "asset_sql_enabled",
    "asset_store_mode",
    "lead_json_enabled",
    "lead_sql_enabled",
    "lead_store_mode",
]
